/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryCreationForm: typeof import('./src/components/creation/category_creation/CategoryCreationForm.vue')['default']
    CreateTaskButton: typeof import('./src/components/creation/task_creation/CreateTaskButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCreationForm: typeof import('./src/components/creation/task_creation/TaskCreationForm.vue')['default']
    TaskItem: typeof import('./src/components/task_display/TaskItem.vue')['default']
    TaskList: typeof import('./src/components/task_display/TaskList.vue')['default']
  }
}
